Repository diuguide/symptom_tracker, pull requests merged in 2020-08, with the labels that each got.

#10 remove config.json from gitignore so that jawsdb works on heroku
  .gitignore
  config/config.json
Labels: backend

#12 add handlebars.js as template engine
  config/config.json
  package-lock.json
  package.json
  server.js
  views/layouts/main.handlebars
  views/userhome.handlebars
Labels: front end

#18 Created basic layout for symptom table
  config/config.json
  public/js/userhome.js
  public/stylesheets/modal.css
  public/stylesheets/style.css
  views/layouts/main.handlebars
  views/userhome.handlebars
Labels: front end

#20 add form handlebars partial for daily symptom reporting
  models/symptom.js
  models/user.js
  public/landing.html
  public/stylesheets/modal.css
  public/stylesheets/style.css
  routes/api-routes.js
  views/layouts/main.handlebars
  views/partials/forms/symptoms.handlebars
  views/userhome.handlebars
Labels: front end

#23 show last 6 days of data on user homepage
  public/js/userhome.js
  public/stylesheets/modal.css
  public/stylesheets/style.css
  routes/html-routes.js
  views/partials/grid/history.handlebars
  views/userhome.handlebars
Labels: backend

#26 Back-end Connection and Modification
  models/symptom.js
  public/landing.html
  routes/api-routes.js
  views/layouts/main.handlebars
  views/partials/forms/symptoms.handlebars
Labels: backend

#25 7 day grid layout updated
  config/config.json
  public/js/userhome.js
  public/stylesheets/modal.css
  public/stylesheets/style.css
  views/layouts/main.handlebars
  views/partials/grid/history.handlebars
  views/userhome.handlebars
Labels: front end

#28 sync server to update tables to match models without performing drops
  server.js
Labels: backend, bug

#27 Connect userhome
  config/config.json
  public/js/userhome.js
  routes/api-routes.js
  routes/html-routes.js
  views/layouts/main.handlebars
  views/partials/forms/symptoms.handlebars
  views/partials/grid/calender.handlebars
  views/partials/grid/history.handlebars
  views/userhome.handlebars
Labels: front end

#31 Update API to allow one entry per day
  package.json
  public/js/userhome.js
  public/landing.html
  routes/api-routes.js
  views/userhome.handlebars
Labels: backend

#33 Tjc/vertical
  config/config.json
  public/js/userhome.js
  public/stylesheets/style.css
  server.js
  views/layouts/main.handlebars
  views/partials/grid/history.handlebars
  views/partials/grid/week.handlebars
  views/userhome.handlebars
Labels: front end

#34 Export to csv
  package-lock.json
  package.json
  routes/api-routes.js
  views/userhome.handlebars
Labels: enhancement, front end

#35 ch cha cha chaaanges
  public/js/userhome.js
  public/stylesheets/style.css
  routes/html-routes.js
  views/partials/grid/week.handlebars
  views/userhome.handlebars
Labels: front end

#36 prettyDate
  server.js
Labels: front end

#40 change bg color to white. change mood 3 to yellow and 4 to blue
  public/js/userhome.js
  public/stylesheets/style.css
Labels: front end

#41 Route-stable
  public/js/login.js
  public/js/signup.js
  public/js/userhome.js
  routes/html-routes.js
Labels: backend, bug, front end

#42 add bug & feature issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#43 update readme and add github community files
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  public/images/home.png
Labels: documentation

#44 Style
  public/js/userhome.js
  public/stylesheets/style.css
  views/partials/grid/week.handlebars
  views/userhome.handlebars
Labels: enhancement, front end
